# Generated by Django 6.0.2 on 2026-02-18 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_alter_listing_chasis_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=100, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='listings.listing')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.featuredpackage')),
            ],
        ),
    ]
