# Generated by Django 4.2.28 on 2026-02-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
