# Generated by Django 6.0.2 on 2026-02-14 12:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=10)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=10)),
                ('trim', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('interior_color', models.CharField(max_length=50)),
                ('chasis_number', models.CharField(max_length=100)),
                ('registered_car', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('exchange_possible', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('body', models.CharField(choices=[('saloon', 'Saloon'), ('hatchback', 'Hatchback'), ('station wagon', 'Station wagon'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('coupe', 'Coupe'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('van', 'Van'), ('microcar', 'Microcar'), ('liftback', 'Liftback'), ('limousine', 'Limousine')], max_length=50)),
                ('drive_train', models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD'), ('4WD', '4WD'), ('Part-Time 4WD', 'Part-Time 4WD'), ('Full-Time 4WD', 'Full-Time 4WD'), ('Hybrid AWD', 'Hybrid AWD'), ('Electric FWD', 'Electric FWD'), ('Electric RWD', 'Electric RWD'), ('Electric AWD', 'Electric AWD')], max_length=50)),
                ('seats_number', models.IntegerField()),
                ('engine_size', models.CharField(max_length=50)),
                ('horse_power', models.CharField(max_length=50)),
                ('negotiation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
                ('features', models.ManyToManyField(blank=True, to='listings.feature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
