# Generated by Django 6.0.2 on 2026-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='chasis_number',
            field=models.CharField(blank=True, help_text='VroomHub will not display this to users', max_length=100, null=True),
        ),
    ]
