# Generated by Django 6.0.3 on 2026-03-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_category_id_alter_feature_id_alter_listing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='body',
            field=models.CharField(choices=[('saloon', 'Saloon'), ('hatchback', 'Hatchback'), ('station wagon', 'Station wagon'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('pickup', 'Pickup'), ('van', 'Van'), ('microcar', 'Microcar'), ('liftback', 'Liftback'), ('limousine', 'Limousine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='chasis_number',
            field=models.CharField(blank=True, help_text='Chrandi Motors will not display this to users', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
